-- Adds two scanner image columns to the panchayat table.
-- Stores filenames (relative to /uploads) of ghar tax and pani tax scanner images.
-- The backend self-heals these columns too (grampanchayat.service.ts).
-- MariaDB IF NOT EXISTS syntax — safe to run multiple times.

ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_TAX_SCANNER` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_TAX_SCANNER` VARCHAR(200) COLLATE utf8mb4_general_ci DEFAULT NULL;

-- Bank/UPI details — one set for gruhkar, one for pani kar (used on /bill-pay when amount > 2000).
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_BANK_NAME` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_IFSC` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_ACCOUNT_NO` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_ACCOUNT_HOLDER` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `GHAR_UPI_ID` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_BANK_NAME` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_IFSC` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_ACCOUNT_NO` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_ACCOUNT_HOLDER` VARCHAR(200) DEFAULT NULL;
ALTER TABLE `panchayat` ADD COLUMN IF NOT EXISTS `PANI_UPI_ID` VARCHAR(200) DEFAULT NULL;
