version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    restart: always
    networks:
      - psm_default1

networks:
  psm_default1:
    external: true
