version: '3.9'
services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
     networks:
      - psm_default

networks:
  psm_default:
    external: true

