ALTER TABLE milkat ADD DELETED_AT DATETIME DEFAULT NULL NULL;

ALTER TABLE milkat_vapar ADD DELETED_AT DATETIME DEFAULT NULL NULL;

ALTER TABLE membermaster ADD DELETED_AT DATETIME DEFAULT NULL NULL;

ALTER TABLE uploaddatadashboard ADD DELETED_AT DATETIME DEFAULT NULL NULL;


ALTER TABLE openplot ADD DELETED_AT DATETIME DEFAULT NULL NULL;